// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.28.0
// source: check_runs.sql

package sqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const countCheckRunsByMonitorAndUser = `-- name: CountCheckRunsByMonitorAndUser :one
SELECT count(*)::bigint
FROM check_runs r
JOIN monitors m ON m.id = r.monitor_id
WHERE r.monitor_id = $1
  AND m.user_id = $2
  AND m.deleted_at IS NULL
`

type CountCheckRunsByMonitorAndUserParams struct {
	MonitorID pgtype.UUID `json:"monitor_id"`
	UserID    pgtype.UUID `json:"user_id"`
}

func (q *Queries) CountCheckRunsByMonitorAndUser(ctx context.Context, arg CountCheckRunsByMonitorAndUserParams) (int64, error) {
	row := q.db.QueryRow(ctx, countCheckRunsByMonitorAndUser, arg.MonitorID, arg.UserID)
	var column_1 int64
	err := row.Scan(&column_1)
	return column_1, err
}

const createCheckRun = `-- name: CreateCheckRun :one
INSERT INTO check_runs (id, monitor_id, config_version, status, scheduled_at)
VALUES ($1, $2, $3, $4, $5)
RETURNING id, monitor_id, config_version, status, scheduled_at, enqueued_at,
    started_at, finished_at, status_code, latency_ms, error_code, error_summary, created_at
`

type CreateCheckRunParams struct {
	ID            pgtype.UUID        `json:"id"`
	MonitorID     pgtype.UUID        `json:"monitor_id"`
	ConfigVersion int32              `json:"config_version"`
	Status        string             `json:"status"`
	ScheduledAt   pgtype.Timestamptz `json:"scheduled_at"`
}

func (q *Queries) CreateCheckRun(ctx context.Context, arg CreateCheckRunParams) (CheckRun, error) {
	row := q.db.QueryRow(ctx, createCheckRun,
		arg.ID,
		arg.MonitorID,
		arg.ConfigVersion,
		arg.Status,
		arg.ScheduledAt,
	)
	var i CheckRun
	err := row.Scan(
		&i.ID,
		&i.MonitorID,
		&i.ConfigVersion,
		&i.Status,
		&i.ScheduledAt,
		&i.EnqueuedAt,
		&i.StartedAt,
		&i.FinishedAt,
		&i.StatusCode,
		&i.LatencyMs,
		&i.ErrorCode,
		&i.ErrorSummary,
		&i.CreatedAt,
	)
	return i, err
}

const getCheckRunByIDAndUser = `-- name: GetCheckRunByIDAndUser :one
SELECT r.id, r.monitor_id, r.config_version, r.status, r.scheduled_at, r.enqueued_at,
    r.started_at, r.finished_at, r.status_code, r.latency_ms, r.error_code,
    r.error_summary, r.created_at
FROM check_runs r
JOIN monitors m ON m.id = r.monitor_id
WHERE r.id = $1 AND m.user_id = $2 AND m.deleted_at IS NULL
`

type GetCheckRunByIDAndUserParams struct {
	ID     pgtype.UUID `json:"id"`
	UserID pgtype.UUID `json:"user_id"`
}

func (q *Queries) GetCheckRunByIDAndUser(ctx context.Context, arg GetCheckRunByIDAndUserParams) (CheckRun, error) {
	row := q.db.QueryRow(ctx, getCheckRunByIDAndUser, arg.ID, arg.UserID)
	var i CheckRun
	err := row.Scan(
		&i.ID,
		&i.MonitorID,
		&i.ConfigVersion,
		&i.Status,
		&i.ScheduledAt,
		&i.EnqueuedAt,
		&i.StartedAt,
		&i.FinishedAt,
		&i.StatusCode,
		&i.LatencyMs,
		&i.ErrorCode,
		&i.ErrorSummary,
		&i.CreatedAt,
	)
	return i, err
}

const listCheckRunsByMonitorAndUser = `-- name: ListCheckRunsByMonitorAndUser :many
SELECT r.id, r.monitor_id, r.config_version, r.status, r.scheduled_at, r.enqueued_at,
    r.started_at, r.finished_at, r.status_code, r.latency_ms, r.error_code,
    r.error_summary, r.created_at
FROM check_runs r
JOIN monitors m ON m.id = r.monitor_id
WHERE r.monitor_id = $1
  AND m.user_id = $2
  AND m.deleted_at IS NULL
ORDER BY r.scheduled_at DESC, r.id DESC
LIMIT $4 OFFSET $3
`

type ListCheckRunsByMonitorAndUserParams struct {
	MonitorID  pgtype.UUID `json:"monitor_id"`
	UserID     pgtype.UUID `json:"user_id"`
	PageOffset int32       `json:"page_offset"`
	PageSize   int32       `json:"page_size"`
}

func (q *Queries) ListCheckRunsByMonitorAndUser(ctx context.Context, arg ListCheckRunsByMonitorAndUserParams) ([]CheckRun, error) {
	rows, err := q.db.Query(ctx, listCheckRunsByMonitorAndUser,
		arg.MonitorID,
		arg.UserID,
		arg.PageOffset,
		arg.PageSize,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []CheckRun{}
	for rows.Next() {
		var i CheckRun
		if err := rows.Scan(
			&i.ID,
			&i.MonitorID,
			&i.ConfigVersion,
			&i.Status,
			&i.ScheduledAt,
			&i.EnqueuedAt,
			&i.StartedAt,
			&i.FinishedAt,
			&i.StatusCode,
			&i.LatencyMs,
			&i.ErrorCode,
			&i.ErrorSummary,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
