// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.28.0
// source: check_engine.sql

package sqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const advanceMonitorNextCheck = `-- name: AdvanceMonitorNextCheck :execrows
UPDATE monitors
SET next_check_at = $1, updated_at = now()
WHERE id = $2 AND deleted_at IS NULL AND status <> 'paused'
`

type AdvanceMonitorNextCheckParams struct {
	NextCheckAt pgtype.Timestamptz `json:"next_check_at"`
	ID          pgtype.UUID        `json:"id"`
}

func (q *Queries) AdvanceMonitorNextCheck(ctx context.Context, arg AdvanceMonitorNextCheckParams) (int64, error) {
	result, err := q.db.Exec(ctx, advanceMonitorNextCheck, arg.NextCheckAt, arg.ID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const completeCheckRun = `-- name: CompleteCheckRun :execrows
UPDATE check_runs
SET status = $1,
    started_at = COALESCE(started_at, now()),
    finished_at = now(),
    error_code = $2,
    error_summary = $3
WHERE id = $4
  AND status IN ('queued', 'running')
`

type CompleteCheckRunParams struct {
	Status       string      `json:"status"`
	ErrorCode    pgtype.Text `json:"error_code"`
	ErrorSummary pgtype.Text `json:"error_summary"`
	ID           pgtype.UUID `json:"id"`
}

func (q *Queries) CompleteCheckRun(ctx context.Context, arg CompleteCheckRunParams) (int64, error) {
	result, err := q.db.Exec(ctx, completeCheckRun,
		arg.Status,
		arg.ErrorCode,
		arg.ErrorSummary,
		arg.ID,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const getCheckRunForProcessing = `-- name: GetCheckRunForProcessing :one
SELECT r.id, r.status, r.config_version,
       m.status AS monitor_status, m.config_version AS monitor_config_version,
       m.deleted_at AS monitor_deleted_at
FROM check_runs r
JOIN monitors m ON m.id = r.monitor_id
WHERE r.id = $1
FOR UPDATE OF r, m
`

type GetCheckRunForProcessingRow struct {
	ID                   pgtype.UUID        `json:"id"`
	Status               string             `json:"status"`
	ConfigVersion        int32              `json:"config_version"`
	MonitorStatus        string             `json:"monitor_status"`
	MonitorConfigVersion int32              `json:"monitor_config_version"`
	MonitorDeletedAt     pgtype.Timestamptz `json:"monitor_deleted_at"`
}

func (q *Queries) GetCheckRunForProcessing(ctx context.Context, id pgtype.UUID) (GetCheckRunForProcessingRow, error) {
	row := q.db.QueryRow(ctx, getCheckRunForProcessing, id)
	var i GetCheckRunForProcessingRow
	err := row.Scan(
		&i.ID,
		&i.Status,
		&i.ConfigVersion,
		&i.MonitorStatus,
		&i.MonitorConfigVersion,
		&i.MonitorDeletedAt,
	)
	return i, err
}

const listDueMonitorsForUpdate = `-- name: ListDueMonitorsForUpdate :many
SELECT id, config_version, interval_minutes, next_check_at
FROM monitors
WHERE deleted_at IS NULL
  AND status <> 'paused'
  AND next_check_at <= now()
ORDER BY next_check_at, id
LIMIT $1
FOR UPDATE SKIP LOCKED
`

type ListDueMonitorsForUpdateRow struct {
	ID              pgtype.UUID        `json:"id"`
	ConfigVersion   int32              `json:"config_version"`
	IntervalMinutes int32              `json:"interval_minutes"`
	NextCheckAt     pgtype.Timestamptz `json:"next_check_at"`
}

func (q *Queries) ListDueMonitorsForUpdate(ctx context.Context, batchSize int32) ([]ListDueMonitorsForUpdateRow, error) {
	rows, err := q.db.Query(ctx, listDueMonitorsForUpdate, batchSize)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListDueMonitorsForUpdateRow{}
	for rows.Next() {
		var i ListDueMonitorsForUpdateRow
		if err := rows.Scan(
			&i.ID,
			&i.ConfigVersion,
			&i.IntervalMinutes,
			&i.NextCheckAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listPendingCheckRunIDs = `-- name: ListPendingCheckRunIDs :many
SELECT id
FROM check_runs
WHERE status = 'queued' AND enqueued_at IS NULL
ORDER BY scheduled_at, id
LIMIT $1
`

func (q *Queries) ListPendingCheckRunIDs(ctx context.Context, batchSize int32) ([]pgtype.UUID, error) {
	rows, err := q.db.Query(ctx, listPendingCheckRunIDs, batchSize)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []pgtype.UUID{}
	for rows.Next() {
		var id pgtype.UUID
		if err := rows.Scan(&id); err != nil {
			return nil, err
		}
		items = append(items, id)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const markCheckRunEnqueued = `-- name: MarkCheckRunEnqueued :execrows
UPDATE check_runs
SET enqueued_at = COALESCE(enqueued_at, now())
WHERE id = $1 AND status = 'queued'
`

func (q *Queries) MarkCheckRunEnqueued(ctx context.Context, id pgtype.UUID) (int64, error) {
	result, err := q.db.Exec(ctx, markCheckRunEnqueued, id)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const markCheckRunRunning = `-- name: MarkCheckRunRunning :execrows
UPDATE check_runs
SET status = 'running', started_at = COALESCE(started_at, now())
WHERE id = $1 AND status = 'queued'
`

func (q *Queries) MarkCheckRunRunning(ctx context.Context, id pgtype.UUID) (int64, error) {
	result, err := q.db.Exec(ctx, markCheckRunRunning, id)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}
