// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.28.0
// source: incidents.sql

package sqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const countIncidentsByMonitorAndUser = `-- name: CountIncidentsByMonitorAndUser :one
SELECT count(*)::bigint
FROM incidents i
JOIN monitors m ON m.id = i.monitor_id
WHERE i.monitor_id = $1
  AND m.user_id = $2
  AND m.deleted_at IS NULL
`

type CountIncidentsByMonitorAndUserParams struct {
	MonitorID pgtype.UUID `json:"monitor_id"`
	UserID    pgtype.UUID `json:"user_id"`
}

func (q *Queries) CountIncidentsByMonitorAndUser(ctx context.Context, arg CountIncidentsByMonitorAndUserParams) (int64, error) {
	row := q.db.QueryRow(ctx, countIncidentsByMonitorAndUser, arg.MonitorID, arg.UserID)
	var column_1 int64
	err := row.Scan(&column_1)
	return column_1, err
}

const createIncident = `-- name: CreateIncident :one
INSERT INTO incidents (id, monitor_id, opened_at, error_code, error_summary)
VALUES ($1, $2, $3, $4, $5)
RETURNING id, monitor_id, opened_at, resolved_at, error_code, error_summary,
    created_at, updated_at
`

type CreateIncidentParams struct {
	ID           pgtype.UUID        `json:"id"`
	MonitorID    pgtype.UUID        `json:"monitor_id"`
	OpenedAt     pgtype.Timestamptz `json:"opened_at"`
	ErrorCode    string             `json:"error_code"`
	ErrorSummary pgtype.Text        `json:"error_summary"`
}

func (q *Queries) CreateIncident(ctx context.Context, arg CreateIncidentParams) (Incident, error) {
	row := q.db.QueryRow(ctx, createIncident,
		arg.ID,
		arg.MonitorID,
		arg.OpenedAt,
		arg.ErrorCode,
		arg.ErrorSummary,
	)
	var i Incident
	err := row.Scan(
		&i.ID,
		&i.MonitorID,
		&i.OpenedAt,
		&i.ResolvedAt,
		&i.ErrorCode,
		&i.ErrorSummary,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listIncidentsByMonitorAndUser = `-- name: ListIncidentsByMonitorAndUser :many
SELECT i.id, i.monitor_id, i.opened_at, i.resolved_at, i.error_code,
    i.error_summary, i.created_at, i.updated_at
FROM incidents i
JOIN monitors m ON m.id = i.monitor_id
WHERE i.monitor_id = $1
  AND m.user_id = $2
  AND m.deleted_at IS NULL
ORDER BY i.opened_at DESC, i.id DESC
LIMIT $4 OFFSET $3
`

type ListIncidentsByMonitorAndUserParams struct {
	MonitorID  pgtype.UUID `json:"monitor_id"`
	UserID     pgtype.UUID `json:"user_id"`
	PageOffset int32       `json:"page_offset"`
	PageSize   int32       `json:"page_size"`
}

func (q *Queries) ListIncidentsByMonitorAndUser(ctx context.Context, arg ListIncidentsByMonitorAndUserParams) ([]Incident, error) {
	rows, err := q.db.Query(ctx, listIncidentsByMonitorAndUser,
		arg.MonitorID,
		arg.UserID,
		arg.PageOffset,
		arg.PageSize,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Incident{}
	for rows.Next() {
		var i Incident
		if err := rows.Scan(
			&i.ID,
			&i.MonitorID,
			&i.OpenedAt,
			&i.ResolvedAt,
			&i.ErrorCode,
			&i.ErrorSummary,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
