// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.28.0

package sqlc

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type CheckRun struct {
	ID            pgtype.UUID        `json:"id"`
	MonitorID     pgtype.UUID        `json:"monitor_id"`
	ConfigVersion int32              `json:"config_version"`
	Status        string             `json:"status"`
	ScheduledAt   pgtype.Timestamptz `json:"scheduled_at"`
	EnqueuedAt    pgtype.Timestamptz `json:"enqueued_at"`
	StartedAt     pgtype.Timestamptz `json:"started_at"`
	FinishedAt    pgtype.Timestamptz `json:"finished_at"`
	StatusCode    pgtype.Int4        `json:"status_code"`
	LatencyMs     pgtype.Int8        `json:"latency_ms"`
	ErrorCode     pgtype.Text        `json:"error_code"`
	ErrorSummary  pgtype.Text        `json:"error_summary"`
	CreatedAt     pgtype.Timestamptz `json:"created_at"`
}

type Incident struct {
	ID           pgtype.UUID        `json:"id"`
	MonitorID    pgtype.UUID        `json:"monitor_id"`
	OpenedAt     pgtype.Timestamptz `json:"opened_at"`
	ResolvedAt   pgtype.Timestamptz `json:"resolved_at"`
	ErrorCode    string             `json:"error_code"`
	ErrorSummary pgtype.Text        `json:"error_summary"`
	CreatedAt    pgtype.Timestamptz `json:"created_at"`
	UpdatedAt    pgtype.Timestamptz `json:"updated_at"`
}

type Monitor struct {
	ID              pgtype.UUID        `json:"id"`
	UserID          pgtype.UUID        `json:"user_id"`
	Name            string             `json:"name"`
	Url             string             `json:"url"`
	IntervalMinutes int32              `json:"interval_minutes"`
	ExpectedStatus  int32              `json:"expected_status"`
	Status          string             `json:"status"`
	ConfigVersion   int32              `json:"config_version"`
	NextCheckAt     pgtype.Timestamptz `json:"next_check_at"`
	LastCheckedAt   pgtype.Timestamptz `json:"last_checked_at"`
	LastLatencyMs   pgtype.Int8        `json:"last_latency_ms"`
	CreatedAt       pgtype.Timestamptz `json:"created_at"`
	UpdatedAt       pgtype.Timestamptz `json:"updated_at"`
	DeletedAt       pgtype.Timestamptz `json:"deleted_at"`
}

type Notification struct {
	ID           pgtype.UUID        `json:"id"`
	UserID       pgtype.UUID        `json:"user_id"`
	MonitorID    pgtype.UUID        `json:"monitor_id"`
	IncidentID   pgtype.UUID        `json:"incident_id"`
	Type         string             `json:"type"`
	DedupeKey    string             `json:"dedupe_key"`
	Title        string             `json:"title"`
	Body         string             `json:"body"`
	ReadAt       pgtype.Timestamptz `json:"read_at"`
	Status       string             `json:"status"`
	QueuedAt     pgtype.Timestamptz `json:"queued_at"`
	SentAt       pgtype.Timestamptz `json:"sent_at"`
	ErrorCode    pgtype.Text        `json:"error_code"`
	ErrorSummary pgtype.Text        `json:"error_summary"`
	CreatedAt    pgtype.Timestamptz `json:"created_at"`
	UpdatedAt    pgtype.Timestamptz `json:"updated_at"`
}

type RefreshToken struct {
	ID        pgtype.UUID        `json:"id"`
	UserID    pgtype.UUID        `json:"user_id"`
	TokenHash []byte             `json:"token_hash"`
	ExpiresAt pgtype.Timestamptz `json:"expires_at"`
	RevokedAt pgtype.Timestamptz `json:"revoked_at"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
}

type User struct {
	ID           pgtype.UUID        `json:"id"`
	Email        string             `json:"email"`
	PasswordHash string             `json:"password_hash"`
	CreatedAt    pgtype.Timestamptz `json:"created_at"`
	UpdatedAt    pgtype.Timestamptz `json:"updated_at"`
}
