// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.28.0
// source: monitors.sql

package sqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const countMonitorsByUser = `-- name: CountMonitorsByUser :one
SELECT count(*)::bigint
FROM monitors
WHERE user_id = $1 AND deleted_at IS NULL
`

func (q *Queries) CountMonitorsByUser(ctx context.Context, userID pgtype.UUID) (int64, error) {
	row := q.db.QueryRow(ctx, countMonitorsByUser, userID)
	var column_1 int64
	err := row.Scan(&column_1)
	return column_1, err
}

const createMonitor = `-- name: CreateMonitor :one
INSERT INTO monitors (
    id, user_id, name, url, interval_minutes, expected_status,
    status, config_version, next_check_at
)
VALUES (
    $1, $2, $3, $4,
    $5, $6,
    COALESCE($7, 'pending'),
    COALESCE($8, 1),
    COALESCE($9, now())
)
RETURNING id, user_id, name, url, interval_minutes, expected_status, status,
    config_version, next_check_at, last_checked_at, last_latency_ms,
    created_at, updated_at, deleted_at
`

type CreateMonitorParams struct {
	ID              pgtype.UUID `json:"id"`
	UserID          pgtype.UUID `json:"user_id"`
	Name            string      `json:"name"`
	Url             string      `json:"url"`
	IntervalMinutes int32       `json:"interval_minutes"`
	ExpectedStatus  int32       `json:"expected_status"`
	Status          interface{} `json:"status"`
	ConfigVersion   interface{} `json:"config_version"`
	NextCheckAt     interface{} `json:"next_check_at"`
}

func (q *Queries) CreateMonitor(ctx context.Context, arg CreateMonitorParams) (Monitor, error) {
	row := q.db.QueryRow(ctx, createMonitor,
		arg.ID,
		arg.UserID,
		arg.Name,
		arg.Url,
		arg.IntervalMinutes,
		arg.ExpectedStatus,
		arg.Status,
		arg.ConfigVersion,
		arg.NextCheckAt,
	)
	var i Monitor
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Name,
		&i.Url,
		&i.IntervalMinutes,
		&i.ExpectedStatus,
		&i.Status,
		&i.ConfigVersion,
		&i.NextCheckAt,
		&i.LastCheckedAt,
		&i.LastLatencyMs,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const getMonitorByIDAndUser = `-- name: GetMonitorByIDAndUser :one
SELECT id, user_id, name, url, interval_minutes, expected_status, status,
    config_version, next_check_at, last_checked_at, last_latency_ms,
    created_at, updated_at, deleted_at
FROM monitors
WHERE id = $1 AND user_id = $2 AND deleted_at IS NULL
`

type GetMonitorByIDAndUserParams struct {
	ID     pgtype.UUID `json:"id"`
	UserID pgtype.UUID `json:"user_id"`
}

func (q *Queries) GetMonitorByIDAndUser(ctx context.Context, arg GetMonitorByIDAndUserParams) (Monitor, error) {
	row := q.db.QueryRow(ctx, getMonitorByIDAndUser, arg.ID, arg.UserID)
	var i Monitor
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Name,
		&i.Url,
		&i.IntervalMinutes,
		&i.ExpectedStatus,
		&i.Status,
		&i.ConfigVersion,
		&i.NextCheckAt,
		&i.LastCheckedAt,
		&i.LastLatencyMs,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const listMonitorsByUser = `-- name: ListMonitorsByUser :many
SELECT id, user_id, name, url, interval_minutes, expected_status, status,
    config_version, next_check_at, last_checked_at, last_latency_ms,
    created_at, updated_at, deleted_at
FROM monitors
WHERE user_id = $1 AND deleted_at IS NULL
ORDER BY created_at DESC, id DESC
LIMIT $3 OFFSET $2
`

type ListMonitorsByUserParams struct {
	UserID     pgtype.UUID `json:"user_id"`
	PageOffset int32       `json:"page_offset"`
	PageSize   int32       `json:"page_size"`
}

func (q *Queries) ListMonitorsByUser(ctx context.Context, arg ListMonitorsByUserParams) ([]Monitor, error) {
	rows, err := q.db.Query(ctx, listMonitorsByUser, arg.UserID, arg.PageOffset, arg.PageSize)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Monitor{}
	for rows.Next() {
		var i Monitor
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.Name,
			&i.Url,
			&i.IntervalMinutes,
			&i.ExpectedStatus,
			&i.Status,
			&i.ConfigVersion,
			&i.NextCheckAt,
			&i.LastCheckedAt,
			&i.LastLatencyMs,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.DeletedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const softDeleteMonitor = `-- name: SoftDeleteMonitor :execrows
UPDATE monitors
SET deleted_at = COALESCE(deleted_at, now()),
    config_version = config_version + 1,
    updated_at = now()
WHERE id = $1 AND user_id = $2 AND deleted_at IS NULL
`

type SoftDeleteMonitorParams struct {
	ID     pgtype.UUID `json:"id"`
	UserID pgtype.UUID `json:"user_id"`
}

func (q *Queries) SoftDeleteMonitor(ctx context.Context, arg SoftDeleteMonitorParams) (int64, error) {
	result, err := q.db.Exec(ctx, softDeleteMonitor, arg.ID, arg.UserID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const updateMonitor = `-- name: UpdateMonitor :one
UPDATE monitors
SET name = $1,
    url = $2,
    interval_minutes = $3,
    expected_status = $4,
    status = $5,
    config_version = $6,
    next_check_at = $7,
    updated_at = now()
WHERE id = $8 AND user_id = $9 AND deleted_at IS NULL
RETURNING id, user_id, name, url, interval_minutes, expected_status, status,
    config_version, next_check_at, last_checked_at, last_latency_ms,
    created_at, updated_at, deleted_at
`

type UpdateMonitorParams struct {
	Name            string             `json:"name"`
	Url             string             `json:"url"`
	IntervalMinutes int32              `json:"interval_minutes"`
	ExpectedStatus  int32              `json:"expected_status"`
	Status          string             `json:"status"`
	ConfigVersion   int32              `json:"config_version"`
	NextCheckAt     pgtype.Timestamptz `json:"next_check_at"`
	ID              pgtype.UUID        `json:"id"`
	UserID          pgtype.UUID        `json:"user_id"`
}

func (q *Queries) UpdateMonitor(ctx context.Context, arg UpdateMonitorParams) (Monitor, error) {
	row := q.db.QueryRow(ctx, updateMonitor,
		arg.Name,
		arg.Url,
		arg.IntervalMinutes,
		arg.ExpectedStatus,
		arg.Status,
		arg.ConfigVersion,
		arg.NextCheckAt,
		arg.ID,
		arg.UserID,
	)
	var i Monitor
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Name,
		&i.Url,
		&i.IntervalMinutes,
		&i.ExpectedStatus,
		&i.Status,
		&i.ConfigVersion,
		&i.NextCheckAt,
		&i.LastCheckedAt,
		&i.LastLatencyMs,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}
