// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.28.0
// source: notifications.sql

package sqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const countNotificationsByUser = `-- name: CountNotificationsByUser :one
SELECT count(*)::bigint FROM notifications WHERE user_id = $1
`

func (q *Queries) CountNotificationsByUser(ctx context.Context, userID pgtype.UUID) (int64, error) {
	row := q.db.QueryRow(ctx, countNotificationsByUser, userID)
	var column_1 int64
	err := row.Scan(&column_1)
	return column_1, err
}

const createNotification = `-- name: CreateNotification :one
INSERT INTO notifications (
    id, user_id, monitor_id, incident_id, type, dedupe_key, title, body
)
VALUES (
    $1, $2, $3, $4,
    $5, $6, $7, $8
)
RETURNING id, user_id, monitor_id, incident_id, type, dedupe_key, title, body,
    read_at, status, queued_at, sent_at, error_code, error_summary,
    created_at, updated_at
`

type CreateNotificationParams struct {
	ID         pgtype.UUID `json:"id"`
	UserID     pgtype.UUID `json:"user_id"`
	MonitorID  pgtype.UUID `json:"monitor_id"`
	IncidentID pgtype.UUID `json:"incident_id"`
	Type       string      `json:"type"`
	DedupeKey  string      `json:"dedupe_key"`
	Title      string      `json:"title"`
	Body       string      `json:"body"`
}

func (q *Queries) CreateNotification(ctx context.Context, arg CreateNotificationParams) (Notification, error) {
	row := q.db.QueryRow(ctx, createNotification,
		arg.ID,
		arg.UserID,
		arg.MonitorID,
		arg.IncidentID,
		arg.Type,
		arg.DedupeKey,
		arg.Title,
		arg.Body,
	)
	var i Notification
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.MonitorID,
		&i.IncidentID,
		&i.Type,
		&i.DedupeKey,
		&i.Title,
		&i.Body,
		&i.ReadAt,
		&i.Status,
		&i.QueuedAt,
		&i.SentAt,
		&i.ErrorCode,
		&i.ErrorSummary,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listNotificationsByUser = `-- name: ListNotificationsByUser :many
SELECT id, user_id, monitor_id, incident_id, type, dedupe_key, title, body,
    read_at, status, queued_at, sent_at, error_code, error_summary,
    created_at, updated_at
FROM notifications
WHERE user_id = $1
ORDER BY created_at DESC, id DESC
LIMIT $3 OFFSET $2
`

type ListNotificationsByUserParams struct {
	UserID     pgtype.UUID `json:"user_id"`
	PageOffset int32       `json:"page_offset"`
	PageSize   int32       `json:"page_size"`
}

func (q *Queries) ListNotificationsByUser(ctx context.Context, arg ListNotificationsByUserParams) ([]Notification, error) {
	rows, err := q.db.Query(ctx, listNotificationsByUser, arg.UserID, arg.PageOffset, arg.PageSize)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Notification{}
	for rows.Next() {
		var i Notification
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.MonitorID,
			&i.IncidentID,
			&i.Type,
			&i.DedupeKey,
			&i.Title,
			&i.Body,
			&i.ReadAt,
			&i.Status,
			&i.QueuedAt,
			&i.SentAt,
			&i.ErrorCode,
			&i.ErrorSummary,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const markNotificationReadByUser = `-- name: MarkNotificationReadByUser :one
UPDATE notifications
SET read_at = COALESCE(read_at, now()), updated_at = now()
WHERE id = $1 AND user_id = $2
RETURNING id, user_id, monitor_id, incident_id, type, dedupe_key, title, body,
    read_at, status, queued_at, sent_at, error_code, error_summary,
    created_at, updated_at
`

type MarkNotificationReadByUserParams struct {
	ID     pgtype.UUID `json:"id"`
	UserID pgtype.UUID `json:"user_id"`
}

func (q *Queries) MarkNotificationReadByUser(ctx context.Context, arg MarkNotificationReadByUserParams) (Notification, error) {
	row := q.db.QueryRow(ctx, markNotificationReadByUser, arg.ID, arg.UserID)
	var i Notification
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.MonitorID,
		&i.IncidentID,
		&i.Type,
		&i.DedupeKey,
		&i.Title,
		&i.Body,
		&i.ReadAt,
		&i.Status,
		&i.QueuedAt,
		&i.SentAt,
		&i.ErrorCode,
		&i.ErrorSummary,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
